export enum Events {

    ADDED_WORKSPACE = "ADDED_WORKSPACE",

    UPDATED_WORKSPACE = "UPDATED_WORKSPACE",

    DELETED_WORKSPACE = "DELETED_WORKSPACE",

    ADDED_REPOSITORY = "ADDED_REPOSITORY",

    UPDATED_REPOSITORY = "UPDATED_REPOSITORY",

    DELETED_REPOSITORY = "DELETED_REPOSITORY",

    CONNECTED_USER_SESSION = "CONNECTED_USER_SESSION",

    DISCONNECTED_USER_SESSION = "DISCONNECTED_USER_SESSION",

    UPDATED_CURRENT_AUTHENTICATED_USER = "UPDATED_CURRENT_AUTHENTICATED_USER",

    ADDED_USER = "ADDED_USER",

    UPDATED_USER = "UPDATED_USER",

    DELETED_USER = "DELETED_USER",

    UPDATED_USER_PREFERENCES = "UPDATED_USER_PREFERENCES",

    ADDED_TRANSLATION_LOCALE="ADDED_TRANSLATION_LOCALE",

    UPDATED_TRANSLATION_LOCALE="UPDATED_TRANSLATION_LOCALE",

    DELETED_TRANSLATION_LOCALE="DELETED_TRANSLATION_LOCALE",
}
