export enum Events {
  ADDED_WORKSPACE = 'ADDED_WORKSPACE',

  UPDATED_WORKSPACE = 'UPDATED_WORKSPACE',

  DELETED_WORKSPACE = 'DELETED_WORKSPACE',

  ADDED_REPOSITORY = 'ADDED_REPOSITORY',

  UPDATED_REPOSITORY = 'UPDATED_REPOSITORY',

  DELETED_REPOSITORY = 'DELETED_REPOSITORY',

  CONNECTED_USER_SESSION = 'CONNECTED_USER_SESSION',

  DISCONNECTED_USER_SESSION = 'DISCONNECTED_USER_SESSION',

  UPDATED_CURRENT_AUTHENTICATED_USER = 'UPDATED_CURRENT_AUTHENTICATED_USER',

  DELETED_CURRENT_AUTHENTICATED_USER = 'DELETED_CURRENT_AUTHENTICATED_USER',

  ADDED_USER = 'ADDED_USER',

  UPDATED_USER = 'UPDATED_USER',

  DELETED_USER = 'DELETED_USER',

  UPDATED_USER_PREFERENCES = 'UPDATED_USER_PREFERENCES',

  ADDED_TRANSLATION_LOCALE = 'ADDED_TRANSLATION_LOCALE',

  UPDATED_TRANSLATION_LOCALE = 'UPDATED_TRANSLATION_LOCALE',

  DELETED_TRANSLATION_LOCALE = 'DELETED_TRANSLATION_LOCALE',

  UPDATED_TRANSLATIONS = 'UPDATED_TRANSLATIONS',

  ADDED_SNAPSHOT = 'ADDED_SNAPSHOT',

  DELETED_SNAPSHOT = 'DELETED_SNAPSHOT',

  ADDED_SCHEDULED_TASK_DEFINITION = 'ADDED_SCHEDULED_TASK_DEFINITION',

  UPDATED_SCHEDULED_TASK_DEFINITION = 'UPDATED_SCHEDULED_TASK_DEFINITION',

  DELETED_SCHEDULED_TASK_DEFINITION = 'DELETED_SCHEDULED_TASK_DEFINITION',

  ADDED_SCHEDULED_TASK_EXECUTION = 'ADDED_SCHEDULED_TASK_EXECUTION',

  DELETED_SCHEDULED_TASK_EXECUTION = 'DELETED_SCHEDULED_TASK_EXECUTION',

  ADDED_DICTIONARY_ENTRY = 'ADDED_DICTIONARY_ENTRY',

  UPDATED_DICTIONARY_ENTRY = 'UPDATED_DICTIONARY_ENTRY',

  DELETED_DICTIONARY_ENTRY = 'DELETED_DICTIONARY_ENTRY',

  ADDED_EXTERNAL_TRANSLATOR_CONFIG = 'ADDED_EXTERNAL_TRANSLATOR_CONFIG',

  UPDATED_EXTERNAL_TRANSLATOR_CONFIG = 'UPDATED_EXTERNAL_TRANSLATOR_CONFIG',

  DELETED_EXTERNAL_TRANSLATOR_CONFIG = 'DELETED_EXTERNAL_TRANSLATOR_CONFIG',
}
