export enum Events {

    UPDATED_WORKSPACE = "UPDATED_WORKSPACE",

    DELETED_WORKSPACE = "DELETED_WORKSPACE",

    UPDATED_REPOSITORY = "UPDATED_REPOSITORY",

    CONNECTED_USER_SESSION = "CONNECTED_USER_SESSION",

    DISCONNECTED_USER_SESSION = "DISCONNECTED_USER_SESSION",

    UPDATED_CURRENT_AUTHENTICATED_USER = "UPDATED_CURRENT_AUTHENTICATED_USER",

    CREATED_USER = "CREATED_USER",

    UPDATED_USER = "UPDATED_USER",

    DELETED_USER = "DELETED_USER"
}
