/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';

/**
 * Description of an authenticated user.
 */
export interface AuthenticatedUser { 
    /**
     * Unique id of the authenticated user.
     */
    id?: string;
    user?: User;
    /**
     * Roles allowed during this session.
     */
    sessionRoles?: Array<AuthenticatedUser.SessionRolesEnum>;
}
export namespace AuthenticatedUser {
    export type SessionRolesEnum = 'MEMBER_OF_ORGANIZATION' | 'MEMBER_OF_REPOSITORY' | 'ADMIN';
    export const SessionRolesEnum = {
        MEMBEROFORGANIZATION: 'MEMBER_OF_ORGANIZATION' as SessionRolesEnum,
        MEMBEROFREPOSITORY: 'MEMBER_OF_REPOSITORY' as SessionRolesEnum,
        ADMIN: 'ADMIN' as SessionRolesEnum
    };
}