/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Config of Azure Translator.
 */
export interface AzureTranslatorConfigDto { 
    /**
     * API key of your Google account.
     */
    subscriptionKey: string;
    /**
     * Region associated to the subscription.
     */
    subscriptionRegion: string;
}