/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GitHubRepositoryCreationRequestDto } from './gitHubRepositoryCreationRequestDto';
import { GitRepositoryCreationRequestDto } from './gitRepositoryCreationRequestDto';

export type Body1Dto = GitHubRepositoryCreationRequestDto | GitRepositoryCreationRequestDto;
