/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Configurations of bundles of a repository.
 */
export interface BundleConfigurationPatchDto {
  /**
   * All the paths that are included when scanning bundles of this type.
   */
  includedPaths?: Array<string>;
  /**
   * All the paths that are ignored when scanning bundles of this type.
   */
  ignoredPaths?: Array<string>;
}
