/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The update of the current user.
 */
export interface CurrentUserPatchDto { 
    /**
     * The new username.
     */
    username?: string;
    /**
     * Name to display for this user (typically: first and last name).
     */
    displayName?: string;
    /**
     * The new email address.
     */
    email?: string;
}