/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * External translation source. This source can be for instance Google Translate.
 */
export interface ExternalTranslationSourceDto { 
    /**
     * Unique id of this source.
     */
    id: string;
    /**
     * Label of this source.
     */
    label: string;
    /**
     * URL pointing to the translation source.
     */
    url: string;
}