/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * External (not from this tool) source of translation.
 */
export interface ExternalTranslatorConfigDto { 
    /**
     * The unique id of this source.
     */
    id: string;
    /**
     * Label associated to this source.
     */
    label: string;
    /**
     * Link URL describing this source.
     */
    linkUrl: string;
    type?: ExternalTranslatorConfigDto.TypeDtoEnum;
}
export namespace ExternalTranslatorConfigDto {
    export type TypeDtoEnum = 'EXTERNAL_GENERIC_REST';
    export const TypeDtoEnum = {
        REST: 'EXTERNAL_GENERIC_REST' as TypeDtoEnum
    };
}