/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RepositoryCreationRequestDto } from './repositoryCreationRequestDto';

/**
 * Request asking the creation of a GitHub repository
 */
export interface GitHubRepositoryCreationRequestDto extends RepositoryCreationRequestDto {
  /**
   * GitHub username of this repository
   */
  username: string;
  /**
   * Repository name
   */
  repository: string;
  /**
   * Access key to use to access this repository
   */
  accessKey?: string;
}
export namespace GitHubRepositoryCreationRequestDto {}
