/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Pull-request on GitHub.
 */
export interface GitHubPullRequestDto {
  /**
   * Name of the repository associated to this request
   */
  repositoryName: string;
  /**
   * Unique id number of this request
   */
  number: number;
  /**
   * The name of the branch containing changes
   */
  currentBranch: string;
  /**
   * The name of the branch where changes should be applied
   */
  targetBranch: string;
  /**
   * Current status of this request
   */
  status: GitHubPullRequestDto.StatusDtoEnum;
}
export namespace GitHubPullRequestDto {
  export type StatusDtoEnum = 'OPEN' | 'CLOSED' | 'MERGED';
  export const StatusDtoEnum = {
    OPEN: 'OPEN' as StatusDtoEnum,
    CLOSED: 'CLOSED' as StatusDtoEnum,
    MERGED: 'MERGED' as StatusDtoEnum,
  };
}
