/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Pull-request on GitHub.
 */
export interface GitHubPullRequest { 
    /**
     * Name of the repository associated to this request
     */
    repositoryName: string;
    /**
     * Unique id number of this request
     */
    number: number;
    /**
     * The name of the branch containing changes
     */
    currentBranch: string;
    /**
     * The name of the branch where changes should be applied
     */
    targetBranch: string;
    /**
     * Current status of this request
     */
    status: GitHubPullRequest.StatusEnum;
}
export namespace GitHubPullRequest {
    export type StatusEnum = 'OPEN' | 'CLOSED' | 'MERGED';
    export const StatusEnum = {
        OPEN: 'OPEN' as StatusEnum,
        CLOSED: 'CLOSED' as StatusEnum,
        MERGED: 'MERGED' as StatusEnum
    };
}