/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RepositoryCreationRequest } from './repositoryCreationRequest';

/**
 * Request asking the update of a GitHub repository
 */
export interface GitHubRepositoryPatchRequest extends RepositoryCreationRequest { 
    /**
     * The default branch to use
     */
    defaultBranch: string;
    /**
     * Access key to use to access this repository
     */
    accessKey?: string;
    /**
     * Access key to use to access this repository
     */
    webHookSecret?: string;
}
export namespace GitHubRepositoryPatchRequest {
}