/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RepositoryDto } from './repositoryDto';

/**
 * GitHub Repository
 */
export interface GitHubRepositoryDto extends RepositoryDto { 
    /**
     * Location URL of this repository
     */
    location: string;
    /**
     * The name of the default branch used to find translations
     */
    defaultBranch: string;
    /**
     * Regex specifying branches that can be scanned by this tool.
     */
    allowedBranches: string;
    /**
     * GitHub username owner of the repository.
     */
    username: string;
    /**
     * GitHub repository name.
     */
    repository: string;
}
export namespace GitHubRepositoryDto {
}
