/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The initial information needed to create an internal user.
 */
export interface InternalUserCreationDto { 
    /**
     * Username used to log in.
     */
    username: string;
    /**
     * Name to display for this user (typically: first and last name).
     */
    displayName: string;
    /**
     * User email address
     */
    email: string;
    /**
     * User password (non encoded)
     */
    password: string;
    /**
     * Assignable user roles
     */
    roles: Array<InternalUserCreationDto.RolesDtoEnum>;
}
export namespace InternalUserCreationDto {
    export type RolesDtoEnum = 'MEMBER_OF_ORGANIZATION' | 'MEMBER_OF_REPOSITORY' | 'ADMIN';
    export const RolesDtoEnum = {
        MEMBEROFORGANIZATION: 'MEMBER_OF_ORGANIZATION' as RolesDtoEnum,
        MEMBEROFREPOSITORY: 'MEMBER_OF_REPOSITORY' as RolesDtoEnum,
        ADMIN: 'ADMIN' as RolesDtoEnum
    };
}