/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Repository that can be of different type.
 */
export interface RepositoryDto { 
    /**
     * Unique id of this repository.
     */
    id: string;
    /**
     * Display name to use for this repository.
     */
    name: string;
    /**
     * All possible repository statuses.
     */
    status: RepositoryDto.StatusDtoEnum;
    type?: RepositoryDto.TypeDtoEnum;
}
export namespace RepositoryDto {
    export type StatusDtoEnum = 'NOT_INITIALIZED' | 'INITIALIZED' | 'INITIALIZATION_ERROR';
    export const StatusDtoEnum = {
        NOTINITIALIZED: 'NOT_INITIALIZED' as StatusDtoEnum,
        INITIALIZED: 'INITIALIZED' as StatusDtoEnum,
        INITIALIZATIONERROR: 'INITIALIZATION_ERROR' as StatusDtoEnum
    };
    export type TypeDtoEnum = 'GIT' | 'GITHUB';
    export const TypeDtoEnum = {
        GIT: 'GIT' as TypeDtoEnum,
        GITHUB: 'GITHUB' as TypeDtoEnum
    };
}