/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Description of the repository.
 */
export interface RepositorySummaryDto { 
    /**
     * Unique id of this repository.
     */
    id: string;
    /**
     * All possible repository statuses.
     */
    status: RepositorySummaryDto.StatusDtoEnum;
    /**
     * Repository name
     */
    name: string;
}
export namespace RepositorySummaryDto {
    export type StatusDtoEnum = 'NOT_INITIALIZED' | 'INITIALIZING' | 'INITIALIZED' | 'INITIALIZATION_ERROR';
    export const StatusDtoEnum = {
        NOTINITIALIZED: 'NOT_INITIALIZED' as StatusDtoEnum,
        INITIALIZING: 'INITIALIZING' as StatusDtoEnum,
        INITIALIZED: 'INITIALIZED' as StatusDtoEnum,
        INITIALIZATIONERROR: 'INITIALIZATION_ERROR' as StatusDtoEnum
    };
}