/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Request asking the creation of a repository
 */
export interface RepositoryCreationRequest { 
    /**
     * The id of the repository to modify
     */
    id: string;
    /**
     * Type of this repository
     */
    type: RepositoryCreationRequest.TypeEnum;
}
export namespace RepositoryCreationRequest {
    export type TypeEnum = 'GIT' | 'GITHUB';
    export const TypeEnum = {
        GIT: 'GIT' as TypeEnum,
        GITHUB: 'GITHUB' as TypeEnum
    };
}