/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Repository that can be of different type.
 */
export interface Repository { 
    id?: string;
    name?: string;
    /**
     * All possible repository statuses.
     */
    status?: Repository.StatusEnum;
    type?: Repository.TypeEnum;
}
export namespace Repository {
    export type StatusEnum = 'NOT_INITIALIZED' | 'INITIALIZING' | 'INITIALIZED' | 'INITIALIZATION_ERROR';
    export const StatusEnum = {
        NOTINITIALIZED: 'NOT_INITIALIZED' as StatusEnum,
        INITIALIZING: 'INITIALIZING' as StatusEnum,
        INITIALIZED: 'INITIALIZED' as StatusEnum,
        INITIALIZATIONERROR: 'INITIALIZATION_ERROR' as StatusEnum
    };
    export type TypeEnum = 'GIT' | 'GITHUB';
    export const TypeEnum = {
        GIT: 'GIT' as TypeEnum,
        GITHUB: 'GITHUB' as TypeEnum
    };
}