/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NonRecurringScheduledTaskTriggerDto } from './nonRecurringScheduledTaskTriggerDto';
import { RecurringScheduledTaskTriggerDto } from './recurringScheduledTaskTriggerDto';

/**
 * Patch of a definition of a scheduled task.
 */
export interface ScheduledTaskDefinitionPatchDto {
  /**
   * Unique id of this kind of persistent task.
   */
  id: string;
  trigger?: NonRecurringScheduledTaskTriggerDto | RecurringScheduledTaskTriggerDto;
}
