/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Request for the creation of a new snapshot.
 */
export interface SnapshotCreationDto { 
    /**
     * Free comment describing the snapshot.
     */
    comment?: string;
    /**
     * Password used to encrypt the ZIP file.
     */
    encryptionPassword?: string;
}