/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Snapshot freezing the state of the tool in a ZIP file.
 */
export interface SnapshotDto { 
    /**
     * The unique id of this snapshot.
     */
    id: string;
    /**
     * The instant when this snapshot has been created.
     */
    createdOn: Date;
    /**
     * The display name of the user that asked this snapshot.
     */
    createdBy: string;
    /**
     * Free end-user comment about this snapshot.
     */
    comment?: string;
}