/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Translation of a text that may have translated from an external source.
 */
export interface TextTranslationDto { 
    /**
     * Unique id of the external source that translated.
     */
    externalSource?: string;
    /**
     * Text before translation.
     */
    originalText: string;
    /**
     * Translation.
     */
    text: string;
}