/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TranslationKeyPatternDto } from './translationKeyPatternDto';
import { TranslationValueRestrictionDto } from './translationValueRestrictionDto';
import { TranslationsSearchPageSpecDto } from './translationsSearchPageSpecDto';

/**
 * Request asking the listing of paginated translations.
 */
export interface TranslationsSearchRequestDto {
  /**
   * Search translations only in those workspaces
   */
  workspaces: Array<string>;
  /**
   * Search translations only in those translations locale ids.
   */
  locales?: Array<string>;
  /**
   * Search translations only in those bundle file ids.
   */
  bundleFiles?: Array<string>;
  /**
   * Specify the criterion that translations must have.
   */
  criterion?: TranslationsSearchRequestDto.CriterionDtoEnum;
  keyPattern?: TranslationKeyPatternDto;
  valueRestriction?: TranslationValueRestrictionDto;
  /**
   * The maximum number of keys for the next page.
   */
  maxKeys?: number;
  pageSpec?: TranslationsSearchPageSpecDto;
}
export namespace TranslationsSearchRequestDto {
  export type CriterionDtoEnum =
    | 'ALL'
    | 'MISSING_TRANSLATIONS'
    | 'TRANSLATIONS_CURRENT_USER_UPDATED'
    | 'UPDATED_TRANSLATIONS';
  export const CriterionDtoEnum = {
    ALL: 'ALL' as CriterionDtoEnum,
    MISSINGTRANSLATIONS: 'MISSING_TRANSLATIONS' as CriterionDtoEnum,
    TRANSLATIONSCURRENTUSERUPDATED: 'TRANSLATIONS_CURRENT_USER_UPDATED' as CriterionDtoEnum,
    UPDATEDTRANSLATIONS: 'UPDATED_TRANSLATIONS' as CriterionDtoEnum,
  };
}
