/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TranslationKeyPattern } from './translationKeyPattern';

/**
 * Request asking the listing of paginated translations.
 */
export interface TranslationsSearchRequest { 
    /**
     * Search translations only in those workspaces
     */
    workspaces: Array<string>;
    /**
     * Search translations only in those translations locale ids.
     */
    locales?: Array<string>;
    /**
     * Specify the criterion that translations must have.
     */
    criterion?: TranslationsSearchRequest.CriterionEnum;
    keyPattern?: TranslationKeyPattern;
    /**
     * The maximum number of keys for the next page.
     */
    maxKeys?: number;
    /**
     * The index of the page to look for (the first page has the index 0)
     */
    pageIndex?: number;
}
export namespace TranslationsSearchRequest {
    export type CriterionEnum = 'ALL' | 'MISSING_TRANSLATIONS' | 'TRANSLATIONS_CURRENT_USER_UPDATED' | 'UPDATED_TRANSLATIONS';
    export const CriterionEnum = {
        ALL: 'ALL' as CriterionEnum,
        MISSINGTRANSLATIONS: 'MISSING_TRANSLATIONS' as CriterionEnum,
        TRANSLATIONSCURRENTUSERUPDATED: 'TRANSLATIONS_CURRENT_USER_UPDATED' as CriterionEnum,
        UPDATEDTRANSLATIONS: 'UPDATED_TRANSLATIONS' as CriterionEnum
    };
}