/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TranslationsPageRowDto } from './translationsPageRowDto';

/**
 * List of paginated translations.
 */
export interface TranslationsPageDto { 
    /**
     * Rows where every row is associated to a bundle key
     */
    rows: Array<TranslationsPageRowDto>;
    /**
     * All the ordered locales (i.e., columns order)
     */
    locales: Array<string>;
    /**
     * The first element of the current page
     */
    firstPageKey?: string;
    /**
     * The last element of the current page
     */
    lastPageKey?: string;
}
