/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Restriction on translations to look for based on a translation value
 */
export interface TranslationValueRestrictionDto { 
    /**
     * The translation value.
     */
    translation: string;
    /**
     * Strategy to use to match values.
     */
    strategy?: TranslationValueRestrictionDto.StrategyDtoEnum;
    /**
     * The locale associated to the translation to look for.
     */
    locale?: string;
}
export namespace TranslationValueRestrictionDto {
    export type StrategyDtoEnum = 'EQUAL' | 'STARTS_WITH' | 'ENDS_WITH' | 'CONTAINS';
    export const StrategyDtoEnum = {
        EQUAL: 'EQUAL' as StrategyDtoEnum,
        STARTSWITH: 'STARTS_WITH' as StrategyDtoEnum,
        ENDSWITH: 'ENDS_WITH' as StrategyDtoEnum,
        CONTAINS: 'CONTAINS' as StrategyDtoEnum
    };
}