/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Description of a new locale associated to a translation (https://tools.ietf.org/html/bcp47)
 */
export interface TranslationLocaleCreationDto { 
    /**
     * The language.
     */
    language: string;
    /**
     * The region of the language.
     */
    region?: string;
    /**
     * The variants in the region.
     */
    variants?: Array<string>;
    /**
     * Icon to be displayed for this locale (library flag-icon-css).
     */
    icon: string;
}