/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Specification of the page to search for.
 */
export interface TranslationsSearchPageSpecDto { 
    /**
     * Flag indicating whether the request asks the next page, or the previous page.
     */
    nextPage?: boolean;
    /**
     * If the search is for the next page, this represents the last element of the previous page, otherwise it's the first element following page.
     */
    keyOtherPage?: string;
}