/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Pattern of a translation key to search for.
 */
export interface TranslationKeyPatternDto { 
    /**
     * Strategy to use to match keys.
     */
    strategy?: TranslationKeyPatternDto.StrategyDtoEnum;
    /**
     * Pattern associated to the strategy.
     */
    pattern?: string;
}
export namespace TranslationKeyPatternDto {
    export type StrategyDtoEnum = 'EQUAL' | 'STARTS_WITH' | 'ENDS_WITH' | 'CONTAINS';
    export const StrategyDtoEnum = {
        EQUAL: 'EQUAL' as StrategyDtoEnum,
        STARTSWITH: 'STARTS_WITH' as StrategyDtoEnum,
        ENDSWITH: 'ENDS_WITH' as StrategyDtoEnum,
        CONTAINS: 'CONTAINS' as StrategyDtoEnum
    };
}