/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Description of the user.
 */
export interface User { 
    /**
     * Id of the user.
     */
    id?: string;
    /**
     * Username of the user.
     */
    username?: string;
    /**
     * Email of the user.
     */
    email?: string;
    /**
     * URL of the user avatar.
     */
    avatarUrl?: string;
    /**
     * User roles.
     */
    roles?: Array<User.RolesEnum>;
    /**
     * All possible user types.
     */
    type?: User.TypeEnum;
}
export namespace User {
    export type RolesEnum = 'MEMBER_OF_ORGANIZATION' | 'MEMBER_OF_REPOSITORY' | 'ADMIN';
    export const RolesEnum = {
        MEMBEROFORGANIZATION: 'MEMBER_OF_ORGANIZATION' as RolesEnum,
        MEMBEROFREPOSITORY: 'MEMBER_OF_REPOSITORY' as RolesEnum,
        ADMIN: 'ADMIN' as RolesEnum
    };
    export type TypeEnum = 'EXTERNAL' | 'INTERNAL';
    export const TypeEnum = {
        EXTERNAL: 'EXTERNAL' as TypeEnum,
        INTERNAL: 'INTERNAL' as TypeEnum
    };
}