/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';

/**
 * Description of a user live session.
 */
export interface UserLiveSession { 
    /**
     * Id of this session.
     */
    id: string;
    user: User;
}