/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Preferences of a user.
 */
export interface UserPreferencesDto { 
    /**
     * The locale to use for the user.
     */
    toolLocale?: UserPreferencesDto.ToolLocaleDtoEnum;
}
export namespace UserPreferencesDto {
    export type ToolLocaleDtoEnum = 'ENGLISH' | 'FRENCH';
    export const ToolLocaleDtoEnum = {
        ENGLISH: 'ENGLISH' as ToolLocaleDtoEnum,
        FRENCH: 'FRENCH' as ToolLocaleDtoEnum
    };
}