/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The update of a user.
 */
export interface UserPatchDto { 
    /**
     * The new username.
     */
    username?: string;
    /**
     * Name to display for this user (typically: first and last name).
     */
    displayName?: string;
    /**
     * The new email address.
     */
    email?: string;
    /**
     * The new password.
     */
    password?: string;
    /**
     * The roles.
     */
    roles?: Array<UserPatchDto.RolesDtoEnum>;
}
export namespace UserPatchDto {
    export type RolesDtoEnum = 'MEMBER_OF_ORGANIZATION' | 'MEMBER_OF_REPOSITORY' | 'ADMIN';
    export const RolesDtoEnum = {
        MEMBEROFORGANIZATION: 'MEMBER_OF_ORGANIZATION' as RolesDtoEnum,
        MEMBEROFREPOSITORY: 'MEMBER_OF_REPOSITORY' as RolesDtoEnum,
        ADMIN: 'ADMIN' as RolesDtoEnum
    };
}