/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BundleFileDto } from './bundleFileDto';

/**
 * A workspace is a place where users can define translations and then submit them for review. A workspace is based on a particular branch.
 */
export interface WorkspaceDto { 
    /**
     * Unique identifier of a workspace.
     */
    id: string;
    /**
     * The branch name on which the workspace is based on.
     */
    branch: string;
    /**
     * The current workspace status. First, the workspace is created, but not initialized. Then, the workspace is initialized and all the translations are retrieved. Once they are edited, they are sent for review.
     */
    status: WorkspaceDto.StatusDtoEnum;
    /**
     * All the bundle files contained in this workspace.
     */
    files: Array<BundleFileDto>;
}
export namespace WorkspaceDto {
    export type StatusDtoEnum = 'NOT_INITIALIZED' | 'INITIALIZED' | 'IN_REVIEW';
    export const StatusDtoEnum = {
        NOTINITIALIZED: 'NOT_INITIALIZED' as StatusDtoEnum,
        INITIALIZED: 'INITIALIZED' as StatusDtoEnum,
        INREVIEW: 'IN_REVIEW' as StatusDtoEnum
    };
}
