/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WorkspaceGitHubReviewDto } from './workspaceGitHubReviewDto';

/**
 * A workspace is a place where users can define translations and then submit them for review. A workspace is based on a particular branch.
 */
export interface WorkspaceDto { 
    /**
     * Unique identifier of a workspace.
     */
    id: string;
    /**
     * The branch name on which the workspace is based on.
     */
    branch: string;
    /**
     * Flag indicating whether this workspace is the default one of the repository.
     */
    defaultWorkspace: boolean;
    /**
     * The current workspace status. First, the workspace is created, but not initialized. Then, the workspace is initialized and all the translations are retrieved. Once they are edited, they are sent for review.
     */
    status: WorkspaceDto.StatusDtoEnum;
    /**
     * The unique id of the associated repository.
     */
    repositoryId: string;
    /**
     * The unique name of the associated repository.
     */
    repositoryName: string;
    /**
     * All possible repository statuses.
     */
    repositoryStatus: WorkspaceDto.RepositoryStatusDtoEnum;
    /**
     * The type of the associated repository.
     */
    repositoryType: WorkspaceDto.RepositoryTypeDtoEnum;
    /**
     * Number of bundles keys in this workspace.
     */
    numberBundleKeys: number;
    /**
     * Indicates whether there are some modifications associated to this workspace.
     */
    dirty: boolean;
    /**
     * The time when the workspace was synchronized with the repository for the last time.
     */
    lastSynchronization?: Date;
    review?: WorkspaceGitHubReviewDto;
}
export namespace WorkspaceDto {
    export type StatusDtoEnum = 'NOT_INITIALIZED' | 'INITIALIZED' | 'IN_REVIEW';
    export const StatusDtoEnum = {
        NOTINITIALIZED: 'NOT_INITIALIZED' as StatusDtoEnum,
        INITIALIZED: 'INITIALIZED' as StatusDtoEnum,
        INREVIEW: 'IN_REVIEW' as StatusDtoEnum
    };
    export type RepositoryStatusDtoEnum = 'NOT_INITIALIZED' | 'INITIALIZED' | 'INITIALIZATION_ERROR';
    export const RepositoryStatusDtoEnum = {
        NOTINITIALIZED: 'NOT_INITIALIZED' as RepositoryStatusDtoEnum,
        INITIALIZED: 'INITIALIZED' as RepositoryStatusDtoEnum,
        INITIALIZATIONERROR: 'INITIALIZATION_ERROR' as RepositoryStatusDtoEnum
    };
    export type RepositoryTypeDtoEnum = 'GIT' | 'GITHUB';
    export const RepositoryTypeDtoEnum = {
        GIT: 'GIT' as RepositoryTypeDtoEnum,
        GITHUB: 'GITHUB' as RepositoryTypeDtoEnum
    };
}
