/**
 * i18n Tool
 * Web API of the i18n tool
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Information about the current review of a workspace.
 */
export interface WorkspaceReviewDto {
  type?: WorkspaceReviewDto.TypeDtoEnum;
}
export namespace WorkspaceReviewDto {
  export type TypeDtoEnum = 'GIT_HUB';
  export const TypeDtoEnum = {
    HUB: 'GIT_HUB' as TypeDtoEnum,
  };
}
